{
 "title": "Pizza Service Dashboard",
 "description": "Metrics for the Pizza Service Backend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Memory and CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"memory\"}",
     "legendFormat": "{{method}} (%)"
    },
    {
     "expr": "{source=\"jwt-pizza-service\", method=\"cpu\"}",
     "legendFormat": "{{method}} (%)"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])*60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "purchase_total{source=\"jwt-pizza-service\", method=\"revenue\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "users_current{source=\"jwt-pizza-service\", method=\"activeusers\"}",
     "legendFormat": "Current active users"
    }
   ]
  },
  {
   "title": "Authentication Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "rate(auth_total{source=\"jwt-pizza-service\"}[1m])*60",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Pizzas ordered, success/fail",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "purchase_total{source=\"jwt-pizza-service\", method!=\"revenue\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latency (Service Endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "latency_current{source=\"jwt-pizza-service\", method=\"serviceEndpoint\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latency (Pizza Creation)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "latency_current{source=\"jwt-pizza-service\", method=\"pizzaCreation\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}